addSbtPlugin("org.playframework" % "sbt-plugin"                % "3.0.3")
addSbtPlugin("org.scalameta"     % "sbt-scalafmt"              % "2.5.2")
addSbtPlugin("ch.epfl.scala"     % "sbt-scalafix"              % "0.12.1")
addSbtPlugin("org.typelevel"     % "sbt-tpolecat"              % "0.5.0")
addSbtPlugin("com.github.cb372"  % "sbt-explicit-dependencies" % "0.3.1")
addSbtPlugin("com.timushev.sbt"  % "sbt-updates"               % "0.6.4")
